app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from members.views import signup_view
from posts.views import post_list_by_tag

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', signup_view, name='signup'),
    path('members/', include('members.urls')),
    path('posts/', include('posts.urls')),
    path('explore/tags/<str:tag>/', post_list_by_tag, name='post-list-by-tag')
]

urlpatterns += static(
    # URL 앞부분이 /media/이면
    prefix=settings.MEDIA_URL,
    # document_root 위치에서 나머지 path에 해당하는 파일을 리턴
    document_root=settings.MEDIA_ROOT
)

app/members/urls.py
from django.urls import path

from . import views

app_name = 'members'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout-view'),
    path('naver-login/', views.naver_login, name='naver-login')
]

app/posts/urls.py
from django.urls import path

from .views import post_list, post_like, post_create, comment_create

app_name = 'posts'

urlpatterns = [
    path('', post_list, name='post-list'),
    path('<int:pk>/like/', post_like, name='post-like'),
    path('create/', post_create, name='post-create'),
    path('<int:post_pk>/comments/create/', comment_create, name='comment-create')
]

app/posts/models.py
import re

from django.db import models

from members.models import User


class Post(models.Model):
    TAG_PATTERN = re.compile(r'#(\w+)')
    """
    인스타그램의 포스트
    """
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(blank=True)

    content_html = models.TextField(blank=True)
    tags = models.ManyToManyField('Tag', verbose_name='해시태그 목록', related_name='posts', blank=True)

    # PostLike를 통한 Many-to-many 구현
    like_users = models.ManyToManyField(
        User,
        through='PostLike',
        related_name='like_post_set'
    )

    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{author} | {created}'.format(
            author=self.author.username,
            created=self.created
        )

    def _save_html(self):
        """
        content 속성의 값을 사용해 해시태그에 해당하는 문자열을 a 태그로 바꿔줌
        """
        self.content_html = re.sub(
            self.TAG_PATTERN,
            r'<a href="/explore/tags/\g<1>/">#\g<1></a>',
            self.content
        )

    def _save_tags(self):
        """
        content에 포함된 해시태그 문자열(예: #Python)의 Tag들을 만듦
        자신의 tags Many-to-many field에 추가
        """
        # instagram, created = Tag.objects.get_or_create(속성)
        # ManyToManyField.set 사용
        tag_name_list = re.findall(self.TAG_PATTERN, self.content)
        tags = [Tag.objects.get_or_create(name=tag_name)[0] for tag_name in tag_name_list]
        self.tags.set(tags)

        # for tag_name in tag_name_list:
        #     tag = Tag.objects.get_or_create(name=tag_name)[0]
        #     self.tags.add(tag)

    def save(self, *args, **kwargs):
        """
        Post 객체가 저장될 때, content 값을 분석해서
        자신의 tags 항목을 적절히 채워줌

        ex) #Django #Python이 온 경우,
        post.tags.all() 시, name이 Django, Python인 Tag 2개 QuerySet이 리턴
        """
        self._save_html()
        super().save(*args, **kwargs)
        self._save_tags()
        # self.tags.clear()


class PostImage(models.Model):
    """
    각 포스트의 사진
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='posts/images')


class PostComment(models.Model):
    """
    각 포스트의 댓글 (Many-to-one)

    postcomment_set <- related_name
    반대쪽 객체에서 사용
    post.postcomment_set

    postcomment <- related_query_name
    반대쪽 QuerySet의 filter 조건 키워드명으로 사용
    Post.objects.filter(postcomment__)

    기본값
    related_name: <모델클래스명의 lowercase>_set
    related_query_name: <모델클래스명의 lowercase>
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()


class PostLike(models.Model):
    """
    사용자가 좋아요 누른 Post 정보를 저장
    Many-to-many 필드를 중간모델(Intermediate Model)을 거쳐 사용
    언제 생성됐는지 extra field로 저장 (created)
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    """
    Many-to-many에서 필드는 Post에 클래스에 작성
    HashTag의 Tag를 담당
    Post 입장에서 post.tags.all()로 연결된 전체 Tag를 불러올 수 있어야 함
    Tag 입장에서 tag.posts.all()로 연결된 전체 Post를 불러올 수 있어야 함

    Django admin에서 결과를 볼 수 있도록 amdin.py에 적절히 내용 기록

    중개모델(Intermediate model) 사용할 필요 없음
    """
    name = models.CharField('태그명', max_length=100)

    def __str__(self):
        return self.name

app/posts/forms.py
from django import forms


class PostCreateForm(forms.Form):
    """
    이 Form에 들어갈 입력 요소
    Image(File)
    Text
    """
    text = forms.CharField(label="text", max_length=200)
    # image = forms.ImageField(label="image")
    image = forms.FileField(widget=forms.ClearableFileInput(
        attrs={
            'multiple': True
        }))

    def save(self):
        pass


class CommentCreateForm(forms.Form):
    comment = forms.CharField(max_length=50, widget=forms.Textarea())

    def save(self, post, author):
        post.postcomment_set.create(author=author, content=self.cleaned_data['comment'])

app/posts/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView

from .forms import PostCreateForm, CommentCreateForm
from .models import Post, PostLike, PostImage, PostComment

app_name = 'posts'


def post_list(request):
    # 1. 로그인 완료 후 이 페이지로 이동
    # 2. index에 접근할 때 로그인이 되어있다면, 이 페이지로 이동
    #     로그인이 되어있는지 확인:
    #         User.is_authenticated가 True인지 체크

    # URL: /posts/ (posts.urls를 사용, config.urls에서 include)
    # Template: templates/posts/post-list.html
    # <h1>Post List</h1>

    # 'posts'라는 키로 모든 Post QuerySet을 전달 (순서는 pk 역순)
    # 전달받은 QuerySet을 순회하며 적절히 Post 내용을 출력

    # posts = Post.objects.all().order_by('-pk')
    posts = Post.objects.order_by('-pk')
    comment_form = CommentCreateForm()

    context = {
        'posts': posts,
        'comment_form': comment_form
    }

    return render(request, 'posts/post-list.html', context)


def post_list_by_tag(request, tag):
    # URL: /explore/tags/<str:tag>/
    # Template: /posts/post-list.html
    # <tag문자열>인 Tag를 자신(post).tags에 갖고 있는 경우인 Post 목록만 돌려줌
    # 이 내용 외에는 위 post_list와 내용 동일
    posts = Post.objects.filter(tags__name__iexact=tag).order_by('-pk')
    comment_form = CommentCreateForm()

    context = {
        'posts': posts,
        'comment_form': comment_form
    }
    return render(request, 'posts/post-list.html', context)


def post_like(request, pk):
    """
    pk가 pk인 Post와 (변수명 post 사용)
    request.user로 전달되는 User(변수명 user 사용)에 대해
파이썬
    1. PostLike(post=post, user=user)인 PostLike 객체가 존재하는지 확인
    2-1. 만약 해당 객체가 이미 있다면, 삭제
    2-2. 만약 해당 객체가 없다면, 새로 생성
    3. 완료 후, posts:post-list로 redirect
    """
    # pk로 Post 가져오기
    # Post.objects.get(키=값)

    # PostLike 객체가 있는지 검사
    # 검색: Django queryset exists
    # PostLike.objects.filter(키1=값1, 키2=값2).exists()

    # 삭제
    # PostLike.objects.filter(조건).delete()

    # redirect
    # return redirect(URL name)

    post = Post.objects.get(pk=pk)
    user = request.user

    post_like_qs = PostLike.objects.filter(post=post, user=user)
    # user, post에 해당하는 PostLike가 있는 경우
    if post_like_qs.exists():
        # 삭제
        post_like_qs.delete()
    # 없는 경우
    else:
        # 생성
        PostLike.objects.create(post=post, user=user)
    return redirect('posts:post-list')


def post_create(request):
    """
    URL: /posts/create/, name='post-create'
    Template: /posts/post-create.html

    forms.PostCreateForm 사용
    :param request:
    :return:
    """
    if request.method == 'POST':
        # 새 Post 생성
        # user는 request.user
        # 전달받는 데이터: image, text
        user = request.user
        # image = request.FILES['image']
        text = request.POST['text']

        # Post 생성 (변수명 post 사용)
        # request.user와 text 사용
        post = Post.objects.create(author=user, content=text)

        # PostImage 생성
        # post와 전달받은 image 사용
        # post_image = PostImage.objects.create(post=post, image=image)

        images = request.FILES.getlist('image')

        for image in images:
            PostImage.objects.create(post=post, image=image)

        # 모든 생성이 완료되면 posts:post-list로 redirect
        return redirect('posts:post-list')
    else:
        form = PostCreateForm()
        context = {
            'form': form
        }
        return render(request, 'posts/post-create.html', context)


def comment_create(request, post_pk):
    # URL: /posts/<int:post_pk>/comments/create/
    # Template: 없음 (post-list.html에 Form 구현)
    # post-list.html 내부에서, 각 Post마다 자신에게 연결된 PostComment 목록을 보여줌

    # 보여주는 형
    # <ul>
    #   <li><b>작성자명</b><span>내용</span></li>
    #   <li><b>작성자명</b><span>내용</span></li>
    # </ul>

    # Form: post.forms.CommentCreateForm

    post = Post.objects.get(pk=post_pk)

    author = request.user
    # content = request.POST['content']
    # post.postcomment_set.create(author=author, content=content)
    form = CommentCreateForm(data=request.POST)
    if form.is_valid():
        print('form >>', form)
        form.save(post=post, author=author)

    return redirect('posts:post-list')

app/templates/posts/post-create.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit">작성</button>
    </form>
</body>
</html>

app/templates/posts/post-list.html
{% extends 'base.html' %}
{% block content %}
<div>User: {{ request.user }}</div>
<div>Authenticated: {{ request.user.is_authenticated }}</div>
<div>
    <a href="{% url 'members:logout-view' %}">로그아웃</a>
</div>
<div>
    <a href="{% url 'posts:post-create' %}">포스트 추가</a>
</div>
<br>

{% for post in posts %}
<div>작성자: {{ post.author }}</div>
<div>작성일시: {{ post.created }}</div>
<div>글내용: {{ post.content_html|safe }}</div>
<br>

<div>
    <!-- 이 post가 가진 모든 PostImage들을 출력
        <img src="~.image.url"> -->
    {% for post_image in post.postimage_set.all %}
    <div>{{ post_image.image }}</div>
    <img src="{{ post_image.image.url }}" alt="">
    {% endfor %}
</div>
<!--    post_like에 POST 요청을 보내는 Form 구현
        - input을 갖지 않음
        - csrf_token만 추가
        - 보내는 곳(action)에 url 태그 적절히 활용
            ex) /posts/1/like/
                /posts/2/like/
            Post의 pk에 따라 위와 같은 URL을 동적으로 생성 -->
<form action="{% url 'posts:post-like' pk=post.pk %}" method="post">
    {% csrf_token %}
    <!--    사용가능한 변수
            - user (User)
            - post (Post) -->

    <!--    Template에서의 메소드 콜
            post.like_users.all() -> post.like_users.all
            호출 구문 제외해야 함 -->

    <!--    in operator
            <변수> in <반복가능 개체(QuerySet 등)>
            -> True/False를 반환 -->

    <!--    user와 post.like_users를 적절히 이용
            현재 request.user가 이 Post의 like_users에 포함되는지 검사
            아래 if/else/endif 구문이 동작하도록 작성 -->

    <!--    user.like_post_set을 이용해서 아래 조건문이 동작하도록 함
            {# {% if user in post.like_users.all %} #}-->
    {% if user in post.like_users.all %}
    <div>좋아요</div>
    {% else %}
    <!--    좋아요 안 눌린 상태-->
    <div>좋아요 취소</div>
    {% endif %}

    {% for user in post.like_users.all %}
    <div>좋아요 누른 유저: {{ user }}</div>
    {% endfor %}

    <button type="submit">좋아요</button>
</form>
<br>
<form action="{% url 'posts:comment-create' post_pk=post.pk %}" method="post">
    {% csrf_token %}
<!--    <input name="hjhg" type="text">-->
    {{ comment_form }}
    <button type="submit">작성</button>
</form>

<ul>
    {% for comment in post.postcomment_set.all %}
    <li><b>{{ comment.author }}</b> <span>{{ comment.content }}</span></li>
    {% endfor %}
</ul>
<hr>
{% endfor %}
{% endblock %}